enable-magisk-update = false

cli-source = "MorpheApp/morphe-desktop"
cli-version = "dev"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "apk"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.youtube"
addon-patches = "bin/update-check.mpp"

[YouTube-Music-Extended]
enabled = true
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.apps.youtube.music"
included-patches = "'Disable music video in album'"
patcher-args = "--options-file=bin/options-ytm-rvx.json"
addon-patches = "bin/update-check.mpp"

[YouTube-Morphe]
enabled = false
app-name = "YouTube"
rv-brand = "Morphe"
build-mode = "apk"
patches-source = "sashade8-ship-it/dual-vot-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.youtube"
addon-patches = "bin/update-check.mpp"

[YouTube-Music-Morphe]
enabled = true
app-name = "YouTube Music"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.apps.youtube.music"
included-patches = "'Clone app'"
patcher-args = "--options-file=bin/options-ytm-morphe.json"
addon-patches = "bin/update-check.mpp"